name: Daily Commit

on:
  schedule:
    - cron: '11 15 * * *'   # runs daily at 15:11 UTC
  workflow_dispatch:         # allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # make sure this matches your default branch

      - name: Add commit by 23f2000524@ds.study.iitm.ac.in
        run: |
          # Generate a random filename
          FILENAME="daily_commit_$(date +%s)_$RANDOM.txt"
          echo "Automated daily commit at $(date)" > $FILENAME

          # Configure Git
          git config user.name "Daily Commit Bot"
          git config user.email "23f2000524@ds.study.iitm.ac.in"

          # Add, commit, and push
          git add $FILENAME
          git commit -m "Automated daily commit: $FILENAME"
          git push
