name: Daily Commit

# Run once per day at 10:30 UTC (change to your preferred time)
on:
  schedule:
    - cron: '15 15 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add commit by 23f2000524@ds.study.iitm.ac.in
        run: |
          echo "Daily commit at $(date)" >> daily_commit.txt
          git config user.name "Daily Commit Bot"
          git config user.email "23f2000524@ds.study.iitm.ac.in"
          git add daily_commit.txt
          git commit -m "Automated daily commit"
          git push
